<div class="col-xs-12 col-sm-9 col-md-8 main-content">
 <section class="multi-line-signature">
  <span class="returntype">
   <a class="" href="dart-async/Future-class.html">
    Future
   </a>
   &lt;&gt;
  </span>
  <span class="name ">
   wait
  </span>
  (
  <wbr>
  <span class="parameter" id="wait-param-futures">
   <span class="type-annotation">
    <a class="" href="dart-core/Iterable-class.html">
     Iterable
    </a>
    &lt;&gt;
   </span>
   <span class="parameter-name">
    futures
   </span>
  </span>
  , {
  <span class="parameter" id="wait-param-eagerError">
   <span class="type-annotation">
    <a class="" href="dart-core/bool-class.html">
     bool
    </a>
   </span>
   <span class="parameter-name">
    eagerError
   </span>
   :
   <span class="default-value">
    false
   </span>
  </span>
  ,
  <span class="parameter" id="wait-param-cleanUp">
   <span class="type-annotation">
    void
   </span>
   <span class="parameter-name">
    cleanUp
   </span>
   (
   <span class="parameter" id="cleanUp-param-successValue">
    <span class="parameter-name">
     successValue
    </span>
   </span>
   )
  </span>
  })
 </section>
 <section class="desc markdown">
  <p>
   Wait for all the given futures to complete and collect their values.
  </p>
  <p>
   Returns a future which will complete once all the futures in a list are
complete. If any of the futures in the list completes with an error,
the resulting future also completes with an error. Otherwise the value
of the returned future will be a list of all the values that were
produced.
  </p>
  <p>
   If
   <code>
    eagerError
   </code>
   is true, the future completes with an error immediately on
the first error from one of the futures. Otherwise all futures must
complete before the returned future is completed (still with the first
error to occur, the remaining errors are silently dropped).
  </p>
  <p>
   If
   <code>
    cleanUp
   </code>
   is provided, in the case of an error, any non-null result of
a successful future is passed to
   <code>
    cleanUp
   </code>
   , which can then release any
resources that the successful operation allocated.
  </p>
  <p>
   The call to
   <code>
    cleanUp
   </code>
   should not throw. If it does, the error will be an
uncaught asynchronous error.
  </p>
 </section>
 <section class="summary source-code" id="source">
  <h2>
   <span>
    Source
   </span>
  </h2>
  <pre>
   <code class="prettyprint lang-dart">
    static Future&lt;List&gt; wait(Iterable&lt;Future&gt; futures,
                         {bool eagerError: false,
                          void cleanUp(successValue)}) {
  final _Future&lt;List&gt; result = new _Future&lt;List&gt;();
  List values;  // Collects the values. Set to null on error.
  int remaining = 0;  // How many futures are we waiting for.
  var error;   // The first error from a future.
  StackTrace stackTrace;  // The stackTrace that came with the error.

  // Handle an error from any of the futures.
  void handleError(theError, theStackTrace) {
    remaining--;
    if (values != null) {
      if (cleanUp != null) {
        for (var value in values) {
          if (value != null) {
            // Ensure errors from cleanUp are uncaught.
            new Future.sync(() { cleanUp(value); });
          }
        }
      }
      values = null;
      if (remaining == 0 || eagerError) {
        result._completeError(theError, theStackTrace);
      } else {
        error = theError;
        stackTrace = theStackTrace;
      }
    } else if (remaining == 0 &amp;&amp; !eagerError) {
      result._completeError(error, stackTrace);
    }
  }

  // As each future completes, put its value into the corresponding
  // position in the list of values.
  for (Future future in futures) {
    int pos = remaining++;
    future.then((Object value) {
      remaining--;
      if (values != null) {
        values[pos] = value;
        if (remaining == 0) {
          result._completeWithValue(values);
        }
      } else {
        if (cleanUp != null &amp;&amp; value != null) {
          // Ensure errors from cleanUp are uncaught.
          new Future.sync(() { cleanUp(value); });
        }
        if (remaining == 0 &amp;&amp; !eagerError) {
          result._completeError(error, stackTrace);
        }
      }
    }, onError: handleError);
  }
  if (remaining == 0) {
    return new Future.value(const []);
  }
  values = new List(remaining);
  return result;
}
   </code>
  </pre>
 </section>
</div>
